name: Run-Tests

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: python -m pip install -r requirements-dev.txt
    - name: Run tests
      run: ./run_tests
